services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  # 2. Redis Caching Service
  redis:
    image: redis:alpine
    container_name: redis-fastapi
    ports:
      - "6379:6379"