"""rename image_file to image_url

Revision ID: d170fa2309b9
Revises: e73d2f964aee
Create Date: 2026-07-31 19:04:42.502953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd170fa2309b9'
down_revision: Union[str, Sequence[str], None] = 'e73d2f964aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image_file', new_column_name="image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image_url', new_column_name="image_file")
    # ### end Alembic commands ###
