"""add onboarding_status column in users table

Revision ID: f7690ef9d97b
Revises: d170fa2309b9
Create Date: 2026-08-12 17:29:41.790135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7690ef9d97b'
down_revision: Union[str, Sequence[str], None] = 'd170fa2309b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_status', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_status')
    # ### end Alembic commands ###
